- styling.md
This changes from chriskempson links to base16-project and replaces
base16-textmate with base16-emacs.
Refs #19
> Update links in styling.md

- CHANGELOG.md
- README.md
This encapsulates a number of smaller README changes.
* Move changelog to CHANGELOG.md
* Add info on the Libera Chat channel
* Drops unofficial builders from the README for now  
Closes #32, Closes #30
> Various README updates

- README.md
Add an `irc://` link for the channel as well as a matrix.to Link for the bridged Matrix room.
> Additional chat links

- builder.md
There are times when the generated colorschemes requires a dark/light variant, such as for VSCode: https://github.com/golf1052/base16-generator/blob/master/themes/base16-apathy-dark.json#L4. Until we add this support to the spec, vscode templates can't use any of our official builders.
`type` isn't an amazing property name, maybe `variant` would work better? My thought was to go for a string value instead of a boolean variant since one day we may have light, dark and medium for example :shrug: 
We'd have to add this field to each [scheme](https://github.com/base16-project/base16-schemes), but I could do that after we merge this. There may be several things I'm missing here, but I just wanted to get a PR out so we could discuss.
> Add light/dark `scheme-variant` support to builder.md

- README.md
We've stopped using IRC and moved to `#tinted-theming:matrix.org` so updated docs to reflect this.
> Replace IRC references with Matrix

- builder.md
This includes a number of tweaks to make the spec clearer and prepare for an updated scheme format.
* Updated definitions/glossary to clarify termonology
* Clarify what data each "input" must provide
* Rename "Scheme Files Spec" to "Legacy Scheme Files Spec"
* Add "filename" to the template config as a way to generate more complicated filenames
* Add definition of the "Slugify" function which works with Unicode
* Language made more generic to avoid talking about a specific schemes repo
Changes I'm not as sure about:
* Drop default value for "variant"
* Add `supported-systems` to template config
Supersedes #55
> Clean up 0.11.0 spec

- CHANGELOG.md
- builder.md
- Add `scheme-slug-underscored`
`scheme-slug-underscored` is being added because it is in use by at least one theme (it is already supported by the Go builder).
- Rename `is_{{ variant }}_variant` to `scheme-is-{{ variant }}-variant`
For consistency reasons, this variable should use dashes and be prefixed with `scheme`.
> Various minor fixes to the 0.11.0-dev spec

- CHANGELOG.md
- builder.md
This tweaks the 0.11 spec to support a new scheme format, while still being able to support the legacy `base16` format.
Additionally, the CHANGELOG has been updated to include a release date.
There is an [open PR](https://github.com/tinted-theming/base16-builder-go/pull/28) to the base16-builder-go repo and a [new schemes repo](https://github.com/tinted-theming/schemes) supporting these changes.
> Final spec 0.11.0 updates

- builder.md
I'm currently working on updating the rust crate [`base16_color_scheme`] from the old [Base 16 spec](https://github.com/chriskempson/base16) to this one.
While implementing the slugify functionality I found that the instruction to lowercase the characters was missing.
This pr fixes it.
[`base16_color_scheme`]: https://github.com/titaniumtraveler/base16_color_scheme
Also the line `Drop all non-alphanumeric and non-dash characters` is a bit ambiguously worded and
something like `Drop all characters that are neither alphanumeric nor dashes` might be better. \
Though that is only a minor nitpick. (I added it as separate commit for convenience.)
> Fix missing Lowercase instruction in Slugify

- styling.md
Fixes #34 by adopting the proposed changes.
In practice, most templates seemed to be doing this anyway, so while this is *technically* a change to the styling spec, it is meant for clarity so in practice no changes to templates will need to be made.
> Update base16 styling spec to clarify current usage

- CONTRIBUTING.md
This Draft PR specifically addresses the point: "Document process for transferring repos in" in issue: https://github.com/tinted-theming/home/issues/84.
It's a draft so we can collaborate and fix any issues before merging. I know this doesn't address the other points in the issue, such as: " Who has final say about the project?" and "Who has final say about each specific template?" which are related. But I wanted to get some momentum with this and if this draft turns into us adding those points, great, otherwise I'll add them in future PRs.
Edit:
I've updated the draft to address more points from the above issue:
- Acceptance criteria for repos
- Obligations maintainers should agree to before transferring over repositories
- Acceptance criteria for PRs
- Document process for transferring …
> Document the process for transferring an external repo into Tinted Theming

- CONTRIBUTING.md
- README.md
- builder.md
As described in https://github.com/tinted-theming/base16-waybar/issues/1 the base16-wabar was forked into the tinted-theming org to automatically maintain it.
As agreed with @JamyGolden  I would help to maintain this repo.
In addition, while reading the CONTRIBUTION.md I fixed some typos.
> fork base16-waybar into tinted-theming org

- .github/workflows/auto-assign-issues.yml
I use this workflow on [Tinty](https://github.com/tinted-theming/tinty) to auto assign people to newly created issues on the repo. Unfortunately we have to hard-code our usernames as assignees into the workflow but I spent some time trying to figure out how to get it to work by providing github org teams as assignees and having the the workflow assign one or many people to the issue (trying to mimic the functionality github has built into it with pull requests) but either I'm missing something obvious or it's not something that has been turned into a github action. I did find one action which claimed it could do it, but I wasn't able to get it to work. 
Anyway, this should at least have us notified when issues are created here.
> Add auto-assign-issues github workflow

- .github/workflows/auto-assign-issues.yml
Instead of hard-coding action with teams, have it read from CODEOWNERS file dynamically. The other repos can reuse this action.
> Adjust action to read teams from .github/CODEOWNERS file

- styling.md
Add extra information to the styling spec to help people create better looking and more consistent themes. I've taken the format from the Base24 [styling.md](https://github.com/tinted-theming/base24/blob/master/styling.md) file and adjusted it.
> Add extra information to styling spec to make it more clear

- CHANGELOG.md
- builder.md
This is technically a breaking change, but was the intended behavior from the beginning. This allows us to add other linting and other tooling to the schemes repo without breaking builders.
> Clarify hidden files and folders should be ignored by builders

- styling.md
- Add "Gray" and "Light Gray" to `Terminal` column for `base03` and `base04`
- Mention bright variants in `Terminal` column and specify bright variants first since we consider these colors bright
- Remove ANSI colour `3` from `base09` since this is specified to be orange, not yellow or bright yellow.
- Put `Terminal` column colors in brackets if they colour name is not referring to an ANSI color name
- Format table to make it easier to read in markdown
- Add backticks to references to `base0x` properties
- Bump styling spec version to `0.4.1`
> Adjust styling spec to specify "bright" ansi names and format document

- builder.md
I'm looking at building some Apple oascripts for [base16-iterm2](https://github.com/tinted-theming/base16-iterm2) to set the themes because right now people have to import the files individually within the iterm2 settings manually (I want to add support to hook up to tinty). In order to set these colors, 16bit color values are required as well as : https://iterm2.com/documentation-scripting.html. Eg: `set foreground color to {65535, 0, 0, 0}`
In attempting to do this I've come across the need for 16bit rgb support.
> Add 16bit rgb variable support

- styling.md
This change doesn't practically change anything for base16, but affects scheme-systems that are a superset of base16. More details about this here: https://github.com/tinted-theming/base24/pull/30
> Specify bright colors first in the styling spec

- README.md
Adds [base16-nwg-dock](https://git.sr.ht/~blueingreen/base16-nwg-dock), [base16-wlr-which-key](https://git.sr.ht/~blueingreen/base16-wlr-which-key).
> docs: Add base16-nwg-dock, base16-wlr-which-key

- CONTRIBUTING_TO_TEMPLATES.md
We can refer to this document from each template repository to make it easier to maintain a template repository CONTRIBUTING document. Currently each repo has its own document and it makes it difficult to change something across the org when something needs to change.
After merging this, we will need to create PRs for each template repository removing the CONTRIBUTING.md file and linking to this file in the tinted-theming/home repository instead.
> Add contributing document for template repositories

- README.md
Adds [base16-lazygit](https://git.sr.ht/~blueingreen/base16-lazygit).
> docs: Add base16-lazygit

- styling.md
Re-orders the definition of `base08`-`base0E` according to https://github.com/tinted-theming/base24/pull/32.
> Redefine specification for bright colors

- styling.md
The extended ANSI colors are implicit and aren't defined anywhere, so terminal template themes tend to copy from each other. This PR gives it more formality.
> Define extended ANSI colors in spec

- README.md
Change https://tinted-theming.github.io/base16-gallery/ to https://tinted-theming.github.io/tinted-gallery/. One works, the other doesn't :-)
> Fix bad gallery URL in README

- README.md
[tinted-nvim](https://github.com/tinted-theming/tinted-nvim) has been created so adding it to readme
> Add tinted-nvim to readme

- styling.md
ANSI code `5` and `13` is usually described as magenta rather than purple:
- https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797#8-16-colors
- https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit
This change is purely semantics and doesn't force any additional prescriptions to the theme authors, since these colors are open to artistic interpretation in the first place. But it can make the configuration of some terminals more natural, because they often specify "magenta" as the color name.
Related: https://github.com/tinted-theming/base24/pull/36
> Rename purple to magenta

- README.md
Is this of interest to include in the tinted readme?
Thanks for the awesome project, btw!
> Add link to `base16-quickshell`
